//>>built
require({cache:{"JBrowse/Store/SeqFeature/GlobalStatsEstimationMixin":function(){define(["dojo/_base/declare","dojo/_base/array","dojo/Deferred"],function(l,q,o){return l(null,{_estimateGlobalStats:function(c){var g=new o,c=c||this.refSeq,j=function(e,j){var a=this,i=0.75*c.start+0.25*c.end,d=Math.max(0,Math.round(i-e/2)),b=Math.min(Math.round(i+e/2),c.end),m=[];this._getFeatures({ref:c.name,start:d,end:b},function(b){m.push(b)},function(){m=q.filter(m,function(m){return m.get("start")>=d&&m.get("end")<=
b});j.call(a,e,{featureDensity:m.length/e,_statsSampleFeatures:m.length,_statsSampleInterval:{ref:c.name,start:d,end:b,length:e}})},function(b){console.error(b);j.call(a,e,null,b)})},e=function(h,k,a){if(a)g.reject(a);else{var i=c.end-c.start;300<=k._statsSampleFeatures||2*h>i||a?g.resolve(k):j.call(this,2*h,e)}};j.call(this,100,e);return g}})})},"JBrowse/Store/SeqFeature/BAM/File":function(){define("dojo/_base/declare,dojo/_base/array,JBrowse/has,JBrowse/Util,JBrowse/Errors,JBrowse/Store/LRUCache,./Util,./LazyFeature".split(","),
function(l,q,o,c,g,j,e,h){var k=function(){console.error.apply(console,arguments)},a=c.fastDeclare({constructor:function(b,m,a){this.minv=b;this.maxv=m;this.bin=a},toUniqueString:function(){return this.minv+".."+this.maxv+" (bin "+this.bin+")"},toString:function(){return this.toUniqueString()},fetchedSize:function(){return this.maxv.block+65536-this.minv.block+1}}),i=e.readInt,d=e.readVirtualOffset;return l(null,{constructor:function(b){this.store=b.store;this.data=b.data;this.bai=b.bai;this.chunkSizeLimit=
b.chunkSizeLimit||5E6},init:function(b){var m=b.success||function(){},a=b.failure||function(b){console.error(b,b.stack)};this._readBAI(dojo.hitch(this,function(){this._readBAMheader(function(){m()},a)}),a)},_readBAI:function(b,m){this.bai.fetch(dojo.hitch(this,function(a){if(a)if(o("typed-arrays")){var f=new Uint8Array(a);if(21578050!=i(f,0))k("Not a BAI file"),m("Not a BAI file");else{var e=i(f,4);this.indices=[];for(var n=8,c=0;c<e;++c){for(var j=n,g=i(f,n),n=n+4,h=0;h<g;++h){i(f,n);for(var l=i(f,
n+4),n=n+8,p=0;p<l;p++)this._findMinAlignment(d(f,n)),n+=16}h=i(f,n);n+=4;this._findMinAlignment(h?d(f,n):null);n+=8*h;if(0<g||0<h)this.indices[c]=new Uint8Array(a,j,n-j)}this.empty=!this.indices.length;b(this.indices,this.minAlignmentVO)}}else k("Web browser does not support typed arrays"),m("Web browser does not support typed arrays");else k("No data read from BAM index (BAI) file"),m("No data read from BAM index (BAI) file")}),m)},_findMinAlignment:function(b){if(b&&(!this.minAlignmentVO||0>this.minAlignmentVO.cmp(b)))this.minAlignmentVO=
b},_readBAMheader:function(b,m){var a=this;a.data.read(0,a.minAlignmentVO?a.minAlignmentVO.block+65535:null,function(f){f=e.unbgzf(f);f=new Uint8Array(f);21840194!=i(f,0)?(k("Not a BAM file"),m("Not a BAM file")):(f=i(f,4),a._readRefSeqs(f+8,262144,b,m))},m)},_readRefSeqs:function(b,a,d,f){var c=this;c.data.read(0,b+a,function(n){var n=e.unbgzf(n),n=new Uint8Array(n),j=i(n,b),g=b+4;c.chrToIndex={};c.indexToChr=[];for(var h=0;h<j;++h){for(var k=i(n,g),l="",p=0;p<k-1;++p)l+=String.fromCharCode(n[g+
4+p]);p=i(n,g+k+4);c.chrToIndex[c.store.browser.regularizeReferenceName(l)]=h;c.indexToChr.push({name:l,length:p});g=g+8+k;if(g>n.length){a*=2;console.warn("BAM header is very big.  Re-fetching "+a+" bytes.");c._readRefSeqs(b,a,d,f);return}}d()},f)},blocksForRange:function(b,m,r){var f=this.indices[b];if(!f)return[];for(var b=function(){for(var b={},a=this._reg2bins(m,r),f=0;f<a.length;++f)b[a[f]]=!0;return b}.call(this),c=[],e=[],j=i(f,0),g=4,h=0;h<j;++h){var k=i(f,g),l=i(f,g+4),g=g+8;if(b[k])for(var p=
0;p<l;++p){var o=d(f,g),q=d(f,g+8);(4681>k?e:c).push(new a(o,q,k));g+=16}else g+=16*l}var t=function(){for(var b=null,a=i(f,g),e=Math.min(m>>14,a-1),a=Math.min(r>>14,a-1);e<=a;++e){var c=d(f,g+4+8*e);if(c&&(!b||0<c.cmp(b)))b=c}return b}();t&&(e=function(b){for(var a=[],m=0;m<b.length;++m){var f=b[m];f.maxv.block>=t.block&&a.push(f)}return a}(e));b=e.concat(c).sort(function(b,a){return b.minv.block-a.minv.block||b.minv.offset-a.minv.offset});c=[];if(b.length){e=b[0];for(j=1;j<b.length;++j)h=b[j],h.minv.block==
e.maxv.block?e=new a(e.minv,h.maxv,"merged"):(c.push(e),e=h);c.push(e)}return c},fetch:function(b,a,d,f,e,c){var b=this.store.browser.regularizeReferenceName(b),b=this.chrToIndex&&this.chrToIndex[b],i;0<=b?(i=this.blocksForRange(b,a,d))||c(new g.Fatal("Error in index fetch")):i=[];i.toString=function(){return this.join(", ")};try{this._fetchChunkFeatures(i,b,a,d,f,e,c)}catch(j){c(j)}},_fetchChunkFeatures:function(b,a,d,f,e,i,h){if(b.length){for(var k=0,l=this.featureCache=this.featureCache||new j({name:"bamFeatureCache",
fillCallback:dojo.hitch(this,"_readChunk"),sizeFunction:function(b){return b.length},maxSize:1E5}),o=0;o<b.length;o++){var s=b[o].fetchedSize();if(s>this.chunkSizeLimit){h(new g.DataOverflow("Too many BAM features. BAM chunk size "+c.commifyNumber(s)+" bytes exceeds chunkSizeLimit of "+c.commifyNumber(this.chunkSizeLimit)+"."));return}}var p;q.forEach(b,function(c){l.get(c,function(c,j){j&&!p&&h(j);if(!(p=p||j)){for(var g=0;g<c.length;g++){var l=c[g];if(l._refID==a)if(l.get("start")>f)break;else l.get("end")>=
d&&e(l)}++k==b.length&&i()}})})}else i()},_readChunk:function(b,a){var d=this,f=[];d.data.read(b.minv.block,b.fetchedSize(),function(c){try{var i=e.unbgzf(c,b.maxv.block-b.minv.block+1);d.readBamFeatures(new Uint8Array(i),b.minv.offset,f,a)}catch(j){a(null,new g.Fatal(j))}},function(b){a(null,new g.Fatal(b))})},readBamFeatures:function(b,a,d,f){for(var c=this,e=0;;)if(a>=b.length){f(d);break}else if(300>=e){var j=i(b,a),j=a+4+j-1;if(j<b.length){var g=new h({store:this.store,file:this,bytes:{byteArray:b,
start:a,end:j}});d.push(g);e++}a=j+1}else{window.setTimeout(function(){c.readBamFeatures(b,a,d,f)},1);break}},_reg2bin:function(b,a){--a;return b>>14==a>>14?4681+(b>>14):b>>17==a>>17?585+(b>>17):b>>20==a>>20?73+(b>>20):b>>23==a>>23?9+(b>>23):b>>26==a>>26?1+(b>>26):0},MAX_BIN:37449,_reg2bins:function(b,a){var d,f=[0];--a;for(d=1+(b>>26);d<=1+(a>>26);++d)f.push(d);for(d=9+(b>>23);d<=9+(a>>23);++d)f.push(d);for(d=73+(b>>20);d<=73+(a>>20);++d)f.push(d);for(d=585+(b>>17);d<=585+(a>>17);++d)f.push(d);for(d=
4681+(b>>14);d<=4681+(a>>14);++d)f.push(d);return f}})})},"JBrowse/Store/SeqFeature/BAM/Util":function(){define(["jszlib/inflate","jszlib/arrayCopy","JBrowse/Util"],function(l,q,o){var c=o.fastDeclare({constructor:function(c,e){this.block=c;this.offset=e},toString:function(){return""+this.block+":"+this.offset},cmp:function(c){return c.block-this.block||c.offset-this.offset}}),g={readInt:function(c,e){return c[e+3]<<24|c[e+2]<<16|c[e+1]<<8|c[e]},readShort:function(c,e){return c[e+1]<<8|c[e]},readFloat:function(c,
e){for(var g=new Uint8Array(4),k=0;4>k;k++)g[k]=c[e+k];return(new Float32Array(g.buffer))[0]},readVirtualOffset:function(g,e){var h=4294967296*(g[e+6]&255)+16777216*(g[e+5]&255)+65536*(g[e+4]&255)+256*(g[e+3]&255)+(g[e+2]&255),k=g[e+1]<<8|g[e];return 0==h&&0==k?null:new c(h,k)},unbgzf:function(c,e){for(var e=Math.min(e||Infinity,c.byteLength-27),h=[],k=0,a=[0];a[0]<e;a[0]+=8){var i=new Uint8Array(c,a[0],18);if(!(31==i[0]&&139==i[1])){console.error("invalid BGZF block header, skipping",i);break}var i=
g.readShort(i,10),i=a[0]+12+i,d;try{d=l(c,i,c.byteLength-i,a)}catch(b){if(/^Z_BUF_ERROR/.test(b.statusString)&&h.length)break;else throw b;}d.byteLength&&(k+=d.byteLength,h.push(d))}if(1==h.length)return h[0];k=new Uint8Array(k);for(d=a=0;d<h.length;++d)i=new Uint8Array(h[d]),q(i,0,k,a,i.length),a+=i.length;return k.buffer}};return g})},"JBrowse/Store/SeqFeature/BAM/LazyFeature":function(){define(["dojo/_base/array","JBrowse/Util","./Util","JBrowse/Model/SimpleFeature"],function(l,q,o,c){var g="=,A,C,x,G,x,x,x,T,x,x,x,x,x,x,N".split(","),
j="M,I,D,N,S,H,P,=,X,?,?,?,?,?,?,?".split(","),e=o.readInt,h=o.readShort,k=o.readFloat;return q.fastDeclare({constructor:function(a){this.store=a.store;this.file=a.file;this.data={type:"match",source:a.store.source};this.bytes={start:a.bytes.start,end:a.bytes.end,byteArray:a.bytes.byteArray};this._coreParse()},get:function(a){return this._get(a.toLowerCase())},_get:function(a){return a in this.data?this.data[a]:this.data[a]=this[a]?this[a]():this._flagMasks[a]?this._parseFlag(a):this._parseTag(a)},
tags:function(){return this._get("_tags")},_tags:function(){this._parseAllTags();var a="seq,seq_reverse_complemented,unmapped,qc_failed,duplicate,secondary_alignment,supplementary_alignment".split(",");this._get("unmapped")||a.push("start","end","strand","score","qual","MQ","CIGAR","length_on_ref");this._get("multi_segment_template")&&a.push("multi_segment_all_aligned","multi_segment_next_segment_unmapped","multi_segment_next_segment_reversed","multi_segment_first","multi_segment_last","next_segment_position");
var a=a.concat(this._tagList||[]),c=this.data,d;for(d in c)c.hasOwnProperty(d)&&"_"!=d[0]&&a.push(d);var b={};return a=l.filter(a,function(a){if(a in this.data&&void 0===this.data[a])return!1;var a=a.toLowerCase(),d=b[a];b[a]=!0;return!d},this)},parent:function(){},children:function(){return this._get("subfeatures")},id:function(){return this._get("name")+"/"+this._get("md")+"/"+this._get("cigar")+"/"+this._get("start")},mq:function(){var a=(this._get("_bin_mq_nl")&65280)>>8;return 255==a?void 0:
a},score:function(){return this._get("mq")},qual:function(){if(!this._get("unmapped")){for(var a=[],c=this.bytes.byteArray,d=this.bytes.start+36+this._get("_l_read_name")+4*this._get("_n_cigar_op")+this._get("_seq_bytes"),b=this._get("seq_length"),e=0;e<b;++e)a.push(c[d+e]);return a.join(" ")}},strand:function(){var a=this._get("xs");return a?"-"==a?-1:1:this._get("seq_reverse_complemented")?-1:1},_l_read_name:function(){return this._get("_bin_mq_nl")&255},_seq_bytes:function(){return this._get("seq_length")+
1>>1},seq:function(){for(var a="",c=this.bytes.byteArray,d=this.bytes.start+36+this._get("_l_read_name")+4*this._get("_n_cigar_op"),b=this._get("_seq_bytes"),e=0;e<b;++e)var h=c[d+e],a=a+g[(h&240)>>4],a=a+g[h&15];return a},name:function(){return this._get("_read_name")},_read_name:function(){for(var a=this.bytes.byteArray,c="",d=this._get("_l_read_name"),b=this.bytes.start+36,e=0;e<d-1;++e)c+=String.fromCharCode(a[b+e]);return c},_n_cigar_op:function(){return this._get("_flag_nc")&65535},cigar:function(){if(!this._get("unmapped")){for(var a=
this.bytes.byteArray,c=this._get("_n_cigar_op"),d=this.bytes.start+36+this._get("_l_read_name"),b="",g=0,h=0;h<c;++h){var f=e(a,d),k=f>>4,f=j[f&15],b=b+(k+f);"H"!=f&&"S"!=f&&"I"!=f&&(g+=k);d+=4}this.data.length_on_ref=g;return b}},next_segment_position:function(){var a=this.file.indexToChr[this._get("_next_refid")];if(a)return a.name+":"+this._get("_next_pos")},subfeatures:function(){if(this.store.createSubfeatures){var a=this._get("cigar");if(a)return this._cigarToSubfeats(a)}},length_on_ref:function(){this._get("cigar");
return this.data.length_on_ref},_flags:function(){return(this.get("_flag_nc")&4294901760)>>16},end:function(){return this._get("start")+(this._get("length_on_ref")||this._get("seq_length")||void 0)},seq_id:function(){return this._get("unmapped")?void 0:(this.file.indexToChr[this._refID]||{}).name},_bin_mq_nl:function(){with(this.bytes)return e(byteArray,start+12)},_flag_nc:function(){with(this.bytes)return e(byteArray,start+16)},seq_length:function(){with(this.bytes)return e(byteArray,start+20)},
_next_refid:function(){with(this.bytes)return e(byteArray,start+24)},_next_pos:function(){with(this.bytes)return e(byteArray,start+28)},template_length:function(){with(this.bytes)return e(byteArray,start+32)},_coreParse:function(){with(this.bytes)this._refID=e(byteArray,start+4),this.data.start=e(byteArray,start+8)},_parseTag:function(a){if(!this._allTagsParsed){this._tagList=this._tagList||[];for(var c=this.bytes.byteArray,d=this._tagOffset||this.bytes.start+36+this._get("_l_read_name")+4*this._get("_n_cigar_op")+
this._get("_seq_bytes")+this._get("seq_length"),b=this.bytes.end;d<b&&j!=a;){var g=String.fromCharCode(c[d],c[d+1]),j=g.toLowerCase(),f=String.fromCharCode(c[d+2]),d=d+3;switch(f.toLowerCase()){case "a":f=String.fromCharCode(c[d]);d+=1;break;case "i":f=e(c,d);d+=4;break;case "c":f=c[d];d+=1;break;case "s":f=h(c,d);d+=2;break;case "f":f=k(c,d);d+=4;break;case "z":case "h":for(f="";d<=b;){var l=c[d++];if(0==l)break;else f+=String.fromCharCode(l)}break;default:console.warn("Unknown BAM tag type '"+f+
"', tags may be incomplete"),f=void 0,d=b}this._tagOffset=d;this._tagList.push(g);if(j==a)return f;this.data[j]=f}this._allTagsParsed=!0}},_parseAllTags:function(){this._parseTag()},_flagMasks:{multi_segment_template:1,multi_segment_all_aligned:2,unmapped:4,multi_segment_next_segment_unmapped:8,seq_reverse_complemented:16,multi_segment_next_segment_reversed:32,multi_segment_first:64,multi_segment_last:128,secondary_alignment:256,qc_failed:512,duplicate:1024,supplementary_alignment:2048},_parseFlag:function(a){return!!(this._get("_flags")&
this._flagMasks[a])},_parseCigar:function(a){return l.map(a.match(/\d+\D/g),function(a){return[a.match(/\D/)[0].toUpperCase(),parseInt(a)]})},_cigarToSubfeats:function(a){for(var e=[],d=this._get("start"),b,a=this._parseCigar(a),g=0;g<a.length;g++){var h=a[g][1],f=a[g][0];"="===f&&(f="E");switch(f){case "M":case "D":case "N":case "E":case "X":b=d+h;break;case "I":b=d}"N"!==f&&(d=new c({data:{type:f,start:d,end:b,strand:this._get("strand"),cigar_op:h+f},parent:this}),e.push(d));d=b}return e}})})},
"JBrowse/Model/SimpleFeature":function(){define("JBrowse/Model/SimpleFeature",["JBrowse/Util"],function(l){var q=0,o=l.fastDeclare({constructor:function(c){c=c||{};this.data=c.data||{};this._parent=c.parent;this._uniqueID=c.id||this.data.uniqueID||(this._parent?this._parent.id()+"_"+q++:"SimpleFeature_"+q++);if(c=this.data.subfeatures)for(var g=0;g<c.length;g++)"function"!=typeof c[g].get&&(c[g]=new o({data:c[g],parent:this}))},get:function(c){return this.data[c]},set:function(c,g){this.data[c]=g},
tags:function(){var c=[],g=this.data,j;for(j in g)g.hasOwnProperty(j)&&c.push(j);return c},id:function(c){if(c)this._uniqueID=c;return this._uniqueID},parent:function(){return this._parent},children:function(){return this.get("subfeatures")}});return o})}}});
define("JBrowse/Store/SeqFeature/BAM","dojo/_base/declare,dojo/_base/array,dojo/_base/Deferred,dojo/_base/lang,JBrowse/has,JBrowse/Util,JBrowse/Store/SeqFeature,JBrowse/Store/DeferredStatsMixin,JBrowse/Store/DeferredFeaturesMixin,JBrowse/Model/XHRBlob,JBrowse/Store/SeqFeature/GlobalStatsEstimationMixin,./BAM/File".split(","),function(l,q,o,c,g,j,e,h,k,a,i,d){return l([e,h,k,i],{constructor:function(b){this.createSubfeatures=b.subfeatures;var e=b.bam||new a(this.resolveUrl(b.urlTemplate||"data.bam")),
h=b.bai||new a(this.resolveUrl(b.baiUrlTemplate||(b.urlTemplate?b.urlTemplate+".bai":"data.bam.bai")));this.bam=new d({store:this,data:e,bai:h,chunkSizeLimit:b.chunkSizeLimit});this.source=(e.url?e.url.match(/\/([^/\#\?]+)($|[\#\?])/)[1]:e.blob?e.blob.name:void 0)||void 0;g("typed-arrays")?this.bam.init({success:c.hitch(this,function(){this._deferred.features.resolve({success:!0});this._estimateGlobalStats().then(c.hitch(this,function(a){this.globalStats=a;this._deferred.stats.resolve({success:!0})}),
c.hitch(this,"_failAllDeferred"))}),failure:c.hitch(this,"_failAllDeferred")}):this._failAllDeferred("This web browser lacks support for JavaScript typed arrays.")},hasRefSeq:function(a,c,d){var e=this,a=e.browser.regularizeReferenceName(a);this._deferred.stats.then(function(){c(a in e.bam.chrToIndex)},d)},_getFeatures:function(a,c,d,e){this.bam.fetch(this.refSeq.name,a.start,a.end,c,d,e)}})});